version: '3'
services:
  nginx:
    image: nginx
    ports:
      - target: 443
        published: 5000
        mode: host
        protocol: tcp
    # ports:
    #   - "5000:443"
    volumes:
      - ./dev-certs/:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  express-api:
    build:
      context: ./
    ports:
      - target: 3000
        published: 5001
